version: "3.2"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/rsyslogd:latest
    hostname: rsyslogd.docker
    volumes:
    - ${ADMIN_PATH:-/opt}/rsyslogd/etc/logrotate.d:/etc/logrotate.d:ro
    - ${ADMIN_PATH:-/opt}/rsyslogd/etc/rsyslog.d:/etc/rsyslog.d:ro
    - logs:/var/log
    ports:
    - 514:514

volumes:
  logs:
networks:
  default:
    external:
      name: app_net
