version: "3"

# define DNS entries to resolve node1 / node2 / node3 (docker host IPs)
#  optionally specify $ADV host/ip and $CLUSTER name

services:
  etcdinfra0:
    image: elcolio/etcd:latest
    restart: always
    hostname: ${ADV:-etcdinfra0}
    volumes:
    - data:/data
    ports:
    - 2379:2379
    - 2380:2380
    - 4001:4001
    - 7001:7001
    network_mode: host
    command: >
      -name ${ADV:-etcdinfra0}
      -advertise-client-urls
         http://${ADV:-etcdinfra0}:2379,http://${ADV:-etcdinfra0}:4001
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -initial-advertise-peer-urls http://{$ADV:-etcdinfra0}:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token ${CLUSTER:-etcd-cluster-1}
      -initial-cluster
         node1=http://node1:2380,node2=http://node2:2380,node3=http://node3:2380
      -initial-cluster-state new

volumes:
  data:
