version: "3"
services:

  app:
    image: nextcloud:12.0.0
    hostname: cloud.ci.net
    environment:
      TZ: US/Pacific
    ports:
    - ${PORT_CLOUD:-18280}:80
    volumes:
    - ${SHARE_PATH}/cloud/html:/var/www/html
    - ${PHOTOS_PATH}/richb:/var/www/html/data/richb/files/Photos
    - ${PHOTOS_PATH}/chitof:/var/www/html/data/chitof/files/Photos
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync-member == true

volumes:
  html:
networks:
  default:
    external:
      name: app_net
