version: "3.1"

services:
  jenkins-master:
    image: dockerhub.instantlinux.net:5000/jenkins-master:latest
    environment:
      TZ: US/Pacific
    ports:
    - 2080:8080
    - 2085:8082
    volumes:
    - jenkinsdata:/var/jenkins_home
    - jenkinsbackup:/var/jenkins_backup
    # TODO: don't mount /var/run/docker.sock
    # root on host!!
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      jenkinsnet:
      app_net:
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync == primary

  jenkins-slave:
    image: dockerhub.instantlinux.net:5000/jenkins-slave:20170403
    environment:
      TZ: US/Pacific
      SWARM_MASTER_URL: http://jenkins-master:8080/
      SWARM_JENKINS_USER: jenkins
      SWARM_JENKINS_PASSWORD: jenkins
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 2
    networks:
      jenkinsnet:
    secrets:
      - repo-push

volumes:
  jenkinsdata:
    external: true
  jenkinsbackup:
    external: true
networks:
  jenkinsnet:
    external: true
  app_net:
    external: true
secrets:
  repo-push:
    external: true
