version: "3"

# same services as xtradb-bootstrap but with CLUSTER_JOIN in first node
# as well as peers

services:
  bootstrap:
    image: percona/percona-xtradb-cluster:5.7.17
    environment:
      TZ: US/Pacific
      CLUSTER_NAME: cluster01
      CLUSTER_JOIN: db_peer
    ports:
    - 13306:3306
    volumes:
    - /var/dvol/xtradb/data:/var/lib/mysql
    - /var/dvol/xtradb/etc:/etc/mysql:ro
    - /var/dvol/xtradb/logs:/var/log/mysql
    deploy:
      placement:
        constraints:
        - node.labels.swarm-sync == primary
    networks:
      dbcluster:
      app_net:

  db_peer:
    image: percona/percona-xtradb-cluster:5.7.17
    environment:
      TZ: US/Pacific
      CLUSTER_NAME: cluster01
    ports:
    - 13406:3306
    volumes:
    - /var/dvol/xtradb/data:/var/lib/mysql
    - /var/dvol/xtradb/etc:/etc/mysql:ro
    - /var/dvol/xtradb/logs:/var/log/mysql
    deploy:
      mode: global
      placement:
        constraints:
        - node.labels.swarm-sync != primary
    networks:
      dbcluster:
      app_net:

  garbd:
    image: gregnuj/garbd:latest
    command: >
      /usr/bin/garbd -a gcomm://bootstrap:4567
      -g cluster01 -o pc.wait_prim=no
    networks:
      dbcluster:

networks:
  app_net:
    external: true
  dbcluster:
    external: true
